/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

import StructureService from '../../../../src/main/resources/META-INF/resources/js/common/services/StructureService';
import {State} from '../../../../src/main/resources/META-INF/resources/js/structure_builder/contexts/StateContext';
import structureBuilderRegistry from '../../../../src/main/resources/META-INF/resources/js/structure_builder/contributors/registry';
import DisplayPageService from '../../../../src/main/resources/META-INF/resources/js/structure_builder/services/DisplayPageService';
import {
	GroupingContainer,
	Structure,
	StructureChild,
	StructureType,
} from '../../../../src/main/resources/META-INF/resources/js/structure_builder/types/Structure';
import {Uuid} from '../../../../src/main/resources/META-INF/resources/js/structure_builder/types/Uuid';
import {Field} from '../../../../src/main/resources/META-INF/resources/js/structure_builder/utils/field';
import getUuid from '../../../../src/main/resources/META-INF/resources/js/structure_builder/utils/getUuid';
import handlePublishStructure from '../../../../src/main/resources/META-INF/resources/js/structure_builder/utils/handlePublishStructure';

jest.mock('frontend-js-components-web', () => ({openToast: jest.fn()}));

jest.mock(
	'../../../../src/main/resources/META-INF/resources/js/common/services/StructureService',
	() => ({
		__esModule: true,
		default: {createStructure: jest.fn(), updateStructure: jest.fn()},
	})
);

jest.mock(
	'../../../../src/main/resources/META-INF/resources/js/structure_builder/services/DisplayPageService',
	() => ({
		__esModule: true,
		default: {
			resetDisplayPage: jest.fn(),
			resetTranslationDisplayPage: jest.fn(),
		},
	})
);

jest.mock(
	'../../../../src/main/resources/META-INF/resources/js/structure_builder/config',
	() => ({
		config: {
			autogeneratedDisplayPage: false,
			editStructureDisplayPageURL: '',
			isReferenced: false,
			structureBuilderURL: '',
		},
	})
);

const EMPTY_HISTORY = {
	deletedChildren: [],
	deletedGroupERCs: [],
	deletedRelationships: [],
	modifiedNames: new Set<Uuid>(),
};

function field(name: string, uuid: Uuid, parent: Uuid): Field {
	return {
		erc: `${name}-erc`,
		indexableConfig: {indexed: false},
		label: {en_US: name},
		localized: false,
		locked: false,
		name,
		parent,
		required: false,
		settings: {},
		type: 'text',
		uuid,
	};
}

const STRUCTURE_UUID = getUuid();

function buildState(type: StructureType, children: StructureChild[]): State {
	const structure: Structure = {
		children: new Map(children.map((child) => [child.uuid, child])),
		erc: 'erc',
		label: {en_US: 'Structure'},
		name: 'Structure',
		path: '',
		spaces: 'all',
		status: 'published',
		system: false,
		type,
		uuid: STRUCTURE_UUID,
		workflows: {},
	};

	return {
		clipboard: null,
		history: EMPTY_HISTORY,
		invalids: new Map(),
		publishedChildren: new Set(),
		renamingItemUuid: null,
		selection: [],
		structure,
		unsavedChanges: false,
	};
}

function publish(state: State) {
	return handlePublishStructure({
		dispatch: jest.fn(),
		objectDefinitions: {},
		showExperienceLink: false,
		showWarnings: false,
		spaces: [],
		staleCache: jest.fn(),
		state,
		validate: () => true,
	});
}

const persist = jest.fn(() => Promise.resolve({error: false}));

describe('handlePublishStructure - contributor delegation', () => {
	beforeAll(() => {
		structureBuilderRegistry.addProvider({
			id: 'test-contributor',
			persist,
			supports: (type) =>
				type !== 'L_CMS_CONTENT_STRUCTURES' &&
				type !== 'L_CMS_FILE_TYPES',
		});
	});

	beforeEach(() => {
		jest.clearAllMocks();

		jest.spyOn(
			Liferay.ThemeDisplay,
			'getDefaultLanguageId'
		).mockReturnValue('en_US');
		jest.spyOn(Liferay.ThemeDisplay, 'getLanguageId').mockReturnValue(
			'en_US'
		);

		(StructureService.updateStructure as jest.Mock).mockResolvedValue({
			error: null,
		});
		(
			DisplayPageService.resetTranslationDisplayPage as jest.Mock
		).mockResolvedValue(undefined);
	});

	afterEach(() => {
		jest.restoreAllMocks();
	});

	it('lets a contributor persist its own data when publishing a contributed structure', async () => {
		const title = field('title', getUuid(), STRUCTURE_UUID);
		const tabUuid = getUuid();
		const sku = field('sku', getUuid(), tabUuid);

		const tab: GroupingContainer = {
			children: new Map([[sku.uuid, sku]]),
			label: {en_US: 'Details'},
			parent: STRUCTURE_UUID,
			type: 'grouping-container',
			uuid: tabUuid,
			variant: 'tab',
		};

		await publish(buildState('L_CUSTOM_STRUCTURES', [title, tab]));

		expect(persist).toHaveBeenCalled();
	});

	it('does not persist for a built-in CMS structure', async () => {
		const title = field('title', getUuid(), STRUCTURE_UUID);

		await publish(buildState('L_CMS_CONTENT_STRUCTURES', [title]));

		expect(persist).not.toHaveBeenCalled();
	});
});
