modified.files.includes[relevant][digital-sales-room-rest-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][digital-sales-room-web-java-rule]=\
    **/*.java,\
    **/test/**,\
    **/testIntegration/**

modified.files.includes[relevant][digital-sales-room-web-playwright-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-sales-room-rest-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-rest-*/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-sales-room-web-java-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-*/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-sales-room-rest-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-rest-*/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-sales-room-web-java-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-*/**/*Test.java

playwright.projects.includes[playwright-js-tomcat101-postgresql163][relevant][digital-sales-room-web-playwright-rule]=\
    digital-sales-room-web.main

relevant.rule.names=\
    digital-sales-room-rest-rule,\
    digital-sales-room-web-java-rule,\
    digital-sales-room-web-playwright-rule

test.batch.names[relevant][digital-sales-room-rest-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][digital-sales-room-web-java-rule]=\
    modules-integration-postgresql163,\
    modules-unit

test.batch.names[relevant][digital-sales-room-web-playwright-rule]=\
    playwright-js-tomcat101-postgresql163

testray.main.component.name=Commerce