modified.files.includes[relevant][digital-sales-room-rest-rule]=**

modules.includes.required.test.batch.class.names.includes[modules-integration-postgresql163][relevant][digital-sales-room-rest-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-rest-*/**/*Test.java

modules.includes.required.test.batch.class.names.includes[modules-unit][relevant][digital-sales-room-rest-rule]=\
    dxp/apps/digital-sales-room/digital-sales-room-rest-*/**/*Test.java

relevant.rule.names=digital-sales-room-rest-rule

test.batch.names[relevant][digital-sales-room-rest-rule]=\
    modules-integration-postgresql163,\
    modules-unit

testray.main.component.name=Commerce