/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditEventPseudonymField service. Represents a row in the &quot;Audit_AuditEventPseudonymField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.audit.storage.model.impl.AuditEventPseudonymFieldModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.audit.storage.model.impl.AuditEventPseudonymFieldImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEventPseudonymField
 * @generated
 */
@ProviderType
public interface AuditEventPseudonymFieldModel
	extends BaseModel<AuditEventPseudonymField>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit event pseudonym field model instance should use the {@link AuditEventPseudonymField} interface instead.
	 */

	/**
	 * Returns the primary key of this audit event pseudonym field.
	 *
	 * @return the primary key of this audit event pseudonym field
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit event pseudonym field.
	 *
	 * @param primaryKey the primary key of this audit event pseudonym field
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit event pseudonym field ID of this audit event pseudonym field.
	 *
	 * @return the audit event pseudonym field ID of this audit event pseudonym field
	 */
	public long getAuditEventPseudonymFieldId();

	/**
	 * Sets the audit event pseudonym field ID of this audit event pseudonym field.
	 *
	 * @param auditEventPseudonymFieldId the audit event pseudonym field ID of this audit event pseudonym field
	 */
	public void setAuditEventPseudonymFieldId(long auditEventPseudonymFieldId);

	/**
	 * Returns the company ID of this audit event pseudonym field.
	 *
	 * @return the company ID of this audit event pseudonym field
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit event pseudonym field.
	 *
	 * @param companyId the company ID of this audit event pseudonym field
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this audit event pseudonym field.
	 *
	 * @return the create date of this audit event pseudonym field
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this audit event pseudonym field.
	 *
	 * @param createDate the create date of this audit event pseudonym field
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the context name of this audit event pseudonym field.
	 *
	 * @return the context name of this audit event pseudonym field
	 */
	@AutoEscape
	public String getContextName();

	/**
	 * Sets the context name of this audit event pseudonym field.
	 *
	 * @param contextName the context name of this audit event pseudonym field
	 */
	public void setContextName(String contextName);

	/**
	 * Returns the name of this audit event pseudonym field.
	 *
	 * @return the name of this audit event pseudonym field
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this audit event pseudonym field.
	 *
	 * @param name the name of this audit event pseudonym field
	 */
	public void setName(String name);

	/**
	 * Returns the value of this audit event pseudonym field.
	 *
	 * @return the value of this audit event pseudonym field
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this audit event pseudonym field.
	 *
	 * @param value the value of this audit event pseudonym field
	 */
	public void setValue(String value);

	/**
	 * Returns the value hash of this audit event pseudonym field.
	 *
	 * @return the value hash of this audit event pseudonym field
	 */
	@AutoEscape
	public String getValueHash();

	/**
	 * Sets the value hash of this audit event pseudonym field.
	 *
	 * @param valueHash the value hash of this audit event pseudonym field
	 */
	public void setValueHash(String valueHash);

	@Override
	public AuditEventPseudonymField cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-1331623524