/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model.impl;

import com.liferay.portal.security.audit.storage.model.AuditEventPseudonymField;
import com.liferay.portal.security.audit.storage.service.AuditEventPseudonymFieldLocalServiceUtil;

/**
 * The extended model base implementation for the AuditEventPseudonymField service. Represents a row in the &quot;Audit_AuditEventPseudonymField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditEventPseudonymFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEventPseudonymFieldImpl
 * @see AuditEventPseudonymField
 * @generated
 */
public abstract class AuditEventPseudonymFieldBaseImpl
	extends AuditEventPseudonymFieldModelImpl
	implements AuditEventPseudonymField {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit event pseudonym field model instance should use the <code>AuditEventPseudonymField</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AuditEventPseudonymFieldLocalServiceUtil.
				addAuditEventPseudonymField(this);
		}
		else {
			AuditEventPseudonymFieldLocalServiceUtil.
				updateAuditEventPseudonymField(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1463819706