/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.security.audit.storage.model.AuditEventPseudonymField;
import com.liferay.portal.security.audit.storage.model.AuditEventPseudonymFieldModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuditEventPseudonymField service. Represents a row in the &quot;Audit_AuditEventPseudonymField&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditEventPseudonymFieldModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditEventPseudonymFieldImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditEventPseudonymFieldImpl
 * @generated
 */
public class AuditEventPseudonymFieldModelImpl
	extends BaseModelImpl<AuditEventPseudonymField>
	implements AuditEventPseudonymFieldModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit event pseudonym field model instance should use the <code>AuditEventPseudonymField</code> interface instead.
	 */
	public static final String TABLE_NAME = "Audit_AuditEventPseudonymField";

	public static final Object[][] TABLE_COLUMNS = {
		{"auditEventPseudonymFieldId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"contextName", Types.VARCHAR}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}, {"valueHash", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("auditEventPseudonymFieldId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("contextName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("valueHash", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Audit_AuditEventPseudonymField (auditEventPseudonymFieldId LONG not null primary key,companyId LONG,createDate DATE null,contextName VARCHAR(75) null,name VARCHAR(75) null,value VARCHAR(255) null,valueHash VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Audit_AuditEventPseudonymField";

	public static final String ENTITY_ALIAS = "auditEventPseudonymField";

	public static final String ORDER_BY_JPQL =
		" ORDER BY auditEventPseudonymField.auditEventPseudonymFieldId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Audit_AuditEventPseudonymField.auditEventPseudonymFieldId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTEXTNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VALUEHASH_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUDITEVENTPSEUDONYMFIELDID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditEventPseudonymFieldModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditEventPseudonymFieldId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditEventPseudonymFieldId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditEventPseudonymFieldId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuditEventPseudonymField.class;
	}

	@Override
	public String getModelClassName() {
		return AuditEventPseudonymField.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuditEventPseudonymField, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuditEventPseudonymField, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditEventPseudonymField, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AuditEventPseudonymField)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuditEventPseudonymField, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuditEventPseudonymField, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuditEventPseudonymField)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuditEventPseudonymField, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuditEventPseudonymField, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map
			<String, Function<AuditEventPseudonymField, Object>>
				_attributeGetterFunctions;

		static {
			Map<String, Function<AuditEventPseudonymField, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AuditEventPseudonymField, Object>>();

			attributeGetterFunctions.put(
				"auditEventPseudonymFieldId",
				AuditEventPseudonymField::getAuditEventPseudonymFieldId);
			attributeGetterFunctions.put(
				"companyId", AuditEventPseudonymField::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", AuditEventPseudonymField::getCreateDate);
			attributeGetterFunctions.put(
				"contextName", AuditEventPseudonymField::getContextName);
			attributeGetterFunctions.put(
				"name", AuditEventPseudonymField::getName);
			attributeGetterFunctions.put(
				"value", AuditEventPseudonymField::getValue);
			attributeGetterFunctions.put(
				"valueHash", AuditEventPseudonymField::getValueHash);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map
			<String, BiConsumer<AuditEventPseudonymField, Object>>
				_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AuditEventPseudonymField, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<AuditEventPseudonymField, ?>>();

			attributeSetterBiConsumers.put(
				"auditEventPseudonymFieldId",
				(BiConsumer<AuditEventPseudonymField, Long>)
					AuditEventPseudonymField::setAuditEventPseudonymFieldId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AuditEventPseudonymField, Long>)
					AuditEventPseudonymField::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AuditEventPseudonymField, Date>)
					AuditEventPseudonymField::setCreateDate);
			attributeSetterBiConsumers.put(
				"contextName",
				(BiConsumer<AuditEventPseudonymField, String>)
					AuditEventPseudonymField::setContextName);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<AuditEventPseudonymField, String>)
					AuditEventPseudonymField::setName);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<AuditEventPseudonymField, String>)
					AuditEventPseudonymField::setValue);
			attributeSetterBiConsumers.put(
				"valueHash",
				(BiConsumer<AuditEventPseudonymField, String>)
					AuditEventPseudonymField::setValueHash);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getAuditEventPseudonymFieldId() {
		return _auditEventPseudonymFieldId;
	}

	@Override
	public void setAuditEventPseudonymFieldId(long auditEventPseudonymFieldId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditEventPseudonymFieldId = auditEventPseudonymFieldId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getContextName() {
		if (_contextName == null) {
			return "";
		}
		else {
			return _contextName;
		}
	}

	@Override
	public void setContextName(String contextName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contextName = contextName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalContextName() {
		return getColumnOriginalValue("contextName");
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	@Override
	public String getValueHash() {
		if (_valueHash == null) {
			return "";
		}
		else {
			return _valueHash;
		}
	}

	@Override
	public void setValueHash(String valueHash) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_valueHash = valueHash;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalValueHash() {
		return getColumnOriginalValue("valueHash");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AuditEventPseudonymField.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuditEventPseudonymField toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuditEventPseudonymField>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditEventPseudonymFieldImpl auditEventPseudonymFieldImpl =
			new AuditEventPseudonymFieldImpl();

		auditEventPseudonymFieldImpl.setAuditEventPseudonymFieldId(
			getAuditEventPseudonymFieldId());
		auditEventPseudonymFieldImpl.setCompanyId(getCompanyId());
		auditEventPseudonymFieldImpl.setCreateDate(getCreateDate());
		auditEventPseudonymFieldImpl.setContextName(getContextName());
		auditEventPseudonymFieldImpl.setName(getName());
		auditEventPseudonymFieldImpl.setValue(getValue());
		auditEventPseudonymFieldImpl.setValueHash(getValueHash());

		auditEventPseudonymFieldImpl.resetOriginalValues();

		return auditEventPseudonymFieldImpl;
	}

	@Override
	public AuditEventPseudonymField cloneWithOriginalValues() {
		AuditEventPseudonymFieldImpl auditEventPseudonymFieldImpl =
			new AuditEventPseudonymFieldImpl();

		auditEventPseudonymFieldImpl.setAuditEventPseudonymFieldId(
			this.<Long>getColumnOriginalValue("auditEventPseudonymFieldId"));
		auditEventPseudonymFieldImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		auditEventPseudonymFieldImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		auditEventPseudonymFieldImpl.setContextName(
			this.<String>getColumnOriginalValue("contextName"));
		auditEventPseudonymFieldImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		auditEventPseudonymFieldImpl.setValue(
			this.<String>getColumnOriginalValue("value"));
		auditEventPseudonymFieldImpl.setValueHash(
			this.<String>getColumnOriginalValue("valueHash"));

		return auditEventPseudonymFieldImpl;
	}

	@Override
	public int compareTo(AuditEventPseudonymField auditEventPseudonymField) {
		long primaryKey = auditEventPseudonymField.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuditEventPseudonymField)) {
			return false;
		}

		AuditEventPseudonymField auditEventPseudonymField =
			(AuditEventPseudonymField)object;

		long primaryKey = auditEventPseudonymField.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuditEventPseudonymField> toCacheModel() {
		AuditEventPseudonymFieldCacheModel auditEventPseudonymFieldCacheModel =
			new AuditEventPseudonymFieldCacheModel();

		auditEventPseudonymFieldCacheModel.auditEventPseudonymFieldId =
			getAuditEventPseudonymFieldId();

		auditEventPseudonymFieldCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			auditEventPseudonymFieldCacheModel.createDate =
				createDate.getTime();
		}
		else {
			auditEventPseudonymFieldCacheModel.createDate = Long.MIN_VALUE;
		}

		auditEventPseudonymFieldCacheModel.contextName = getContextName();

		String contextName = auditEventPseudonymFieldCacheModel.contextName;

		if ((contextName != null) && (contextName.length() == 0)) {
			auditEventPseudonymFieldCacheModel.contextName = null;
		}

		auditEventPseudonymFieldCacheModel.name = getName();

		String name = auditEventPseudonymFieldCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			auditEventPseudonymFieldCacheModel.name = null;
		}

		auditEventPseudonymFieldCacheModel.value = getValue();

		String value = auditEventPseudonymFieldCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			auditEventPseudonymFieldCacheModel.value = null;
		}

		auditEventPseudonymFieldCacheModel.valueHash = getValueHash();

		String valueHash = auditEventPseudonymFieldCacheModel.valueHash;

		if ((valueHash != null) && (valueHash.length() == 0)) {
			auditEventPseudonymFieldCacheModel.valueHash = null;
		}

		return auditEventPseudonymFieldCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AuditEventPseudonymField, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AuditEventPseudonymField, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditEventPseudonymField, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(AuditEventPseudonymField)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, AuditEventPseudonymField>
				_escapedModelProxyProviderFunction =
					ProxyUtil.getProxyProviderFunction(
						AuditEventPseudonymField.class, ModelWrapper.class);

	}

	private long _auditEventPseudonymFieldId;
	private long _companyId;
	private Date _createDate;
	private String _contextName;
	private String _name;
	private String _value;
	private String _valueHash;

	public <T> T getColumnValue(String columnName) {
		Function<AuditEventPseudonymField, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuditEventPseudonymField)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"auditEventPseudonymFieldId", _auditEventPseudonymFieldId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("contextName", _contextName);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
		_columnOriginalValues.put("valueHash", _valueHash);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("auditEventPseudonymFieldId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("contextName", 8L);

		columnBitmasks.put("name", 16L);

		columnBitmasks.put("value", 32L);

		columnBitmasks.put("valueHash", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuditEventPseudonymField _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-556172706